//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fontisso.NET.I18n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fontisso.NET.I18n.UI", typeof(UI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Button_Ok {
            get {
                return ResourceManager.GetString("Button_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patch.
        /// </summary>
        public static string Button_Patch {
            get {
                return ResourceManager.GetString("Button_Patch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose file.
        /// </summary>
        public static string Button_PickFile {
            get {
                return ResourceManager.GetString("Button_PickFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Dialog_Error {
            get {
                return ResourceManager.GetString("Dialog_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Dialog_Info {
            get {
                return ResourceManager.GetString("Dialog_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maniacs Patch (v210519+).
        /// </summary>
        public static string EngineType_ModernManiacs {
            get {
                return ResourceManager.GetString("EngineType_ModernManiacs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vanilla 2k3 (Steam).
        /// </summary>
        public static string EngineType_ModernVanilla2k3 {
            get {
                return ResourceManager.GetString("EngineType_ModernVanilla2k3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maniacs Patch (old).
        /// </summary>
        public static string EngineType_OldManiacs {
            get {
                return ResourceManager.GetString("EngineType_OldManiacs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old vanilla 2k3.
        /// </summary>
        public static string EngineType_OldVanilla2k3 {
            get {
                return ResourceManager.GetString("EngineType_OldVanilla2k3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vanilla 2k.
        /// </summary>
        public static string EngineType_Vanilla2k {
            get {
                return ResourceManager.GetString("EngineType_Vanilla2k", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create backup.
        /// </summary>
        public static string Error_CannotCreateBackup {
            get {
                return ResourceManager.GetString("Error_CannotCreateBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot patch file: {0}.
        /// </summary>
        public static string Error_CannotPatch {
            get {
                return ResourceManager.GetString("Error_CannotPatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot patch file (code {0}): {1}.
        /// </summary>
        public static string Error_CannotPatchWin32 {
            get {
                return ResourceManager.GetString("Error_CannotPatchWin32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine too old to be patched. Only versions 1.12 and up are supported..
        /// </summary>
        public static string Error_EngineTooOld {
            get {
                return ResourceManager.GetString("Error_EngineTooOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found: {0}.
        /// </summary>
        public static string Error_FileNotFound {
            get {
                return ResourceManager.GetString("Error_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported file format. Expected either RPG_RT.exe or ultimate_rt_eb.dll.
        /// </summary>
        public static string Error_Not2k3File {
            get {
                return ResourceManager.GetString("Error_Not2k3File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected exception occurred: {0}.
        /// </summary>
        public static string Error_Unhandled {
            get {
                return ResourceManager.GetString("Error_Unhandled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag and drop a file or use the button below.
        /// </summary>
        public static string FileInput_Description {
            get {
                return ResourceManager.GetString("FileInput_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag and drop here.
        /// </summary>
        public static string FileInput_DragAndDropHere {
            get {
                return ResourceManager.GetString("FileInput_DragAndDropHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string FontPicker_SearchPlaceholder {
            get {
                return ResourceManager.GetString("FontPicker_SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose file.
        /// </summary>
        public static string Header_PickFile {
            get {
                return ResourceManager.GetString("Header_PickFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose font.
        /// </summary>
        public static string Header_PickFont {
            get {
                return ResourceManager.GetString("Header_PickFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Header_Preview {
            get {
                return ResourceManager.GetString("Header_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File patched successfully! Created backup: {0}.
        /// </summary>
        public static string Success_Patched {
            get {
                return ResourceManager.GetString("Success_Patched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quick brown fox jumps over the lazy dog.
        /// </summary>
        public static string Summary_SampleText {
            get {
                return ResourceManager.GetString("Summary_SampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type any text.
        /// </summary>
        public static string TextInput_SampleTextPlaceholder {
            get {
                return ResourceManager.GetString("TextInput_SampleTextPlaceholder", resourceCulture);
            }
        }
    }
}
